version: "3.9"

services:
  app:
    image: ${DOCKERHUB_USER}/meu-gerenciador:${IMAGE_TAG}
    ports:
      - "5000:5000"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      IMAGE_TAG: ${IMAGE_TAG}
    depends_on:
      - db
    networks:
      - rede
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede
    restart: always

volumes:
  postgres_data:

networks:
  rede:
