name: CI/CD - Deploy FastAPI

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ---------------------
      # Checkout do cÃ³digo
      # ---------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # ---------------------
      # Login no Docker Hub
      # ---------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------------------
      # Build da imagem
      # ---------------------
      - name: Build Docker image
        run: docker buildx build -t ${{ secrets.DOCKERHUB_USER }}/tasks-api:${{ github.sha }} .

      # ---------------------
      # Push para o Docker Hub
      # ---------------------
      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USER }}/meu-gerenciador:${{ github.sha }}

      # ---------------------
      # Copiar docker-compose.prod.yml para o servidor
      # ---------------------
      - name: Copy docker-compose.prod.yml to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.prod.yml"
          target: "~/"

      # ---------------------
      # Deploy no servidor
      # ---------------------
      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "ðŸ”¥ Atualizando deploy..."

            # Para e remove containers antigos
            docker compose -f docker-compose.prod.yml down || true

            # Puxar imagem nova
            docker pull ${{ secrets.DOCKERHUB_USER }}/meu-gerenciador:${{ github.sha }}

            # Sobe os serviÃ§os
            IMAGE_TAG=${{ github.sha }} POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} docker compose -f docker-compose.prod.yml up -d --force-recreate

            echo "ðŸš€ Deploy finalizado!"

